from loyalty.application.exceptions.base import ApplicationError


class LoyaltyDoesNotExistError(ApplicationError): ...


class LoyaltyAlreadyExistsError(ApplicationError): ...


class LoyaltyWrongDateTimeError(ApplicationError): ...


class ForeignBusinessBranchesError(ApplicationError): ...
