services:
    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        depends_on:
            - api
            - swagger-ui

    swagger-ui:
        extends:
            file: docker-compose.base.yml
            service: swagger-ui
        depends_on:
            - api

    tests:
        restart: no
        extends:
            file: docker-compose.base.yml
            service: code
        container_name: tests
        command: [ "pytest", "-vvv" ]
        environment:
            - API_URL=http://nginx:80
        depends_on:
            nginx:
                condition: service_healthy

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        depends_on:
            db:
                condition: service_healthy

    db:
        extends:
            file: docker-compose.base.yml
            service: db
