services:
    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        volumes:
            - static_volume:/var/www/loyalty/static
        depends_on:
            - api
            - swagger-ui

    swagger-ui:
        extends:
            file: docker-compose.base.yml
            service: swagger-ui
        depends_on:
            - api

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        volumes:
            - static_volume:/home/app/src/loyalty/presentation/web/static
        depends_on:
            db:
                condition: service_healthy

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        volumes:
            - pg_data:/var/lib/postgresql/data/

volumes:
    pg_data:
    static_volume:
