services:
    nginx:
        image: nginx:1.29.1
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./.config/dev/nginx.dev.conf:/etc/nginx/nginx.conf
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/ping/"]
            interval: 4s

    swagger-ui:
        container_name: swagger-ui
        build:
            dockerfile: Dockerfile.swagger
        expose:
            - 8080
        restart: unless-stopped

    code:
        restart: on-failure
        build: .
        env_file:
            - "./.config/dev/.env.dev"
        volumes:
            - "./src/loyalty/adapters/db/alembic/migrations/versions/:/home/app/src/loyalty/adapters/db/alembic/migrations/versions/"

    migrations:
        container_name: migrations
        command: ["crudik", "migrations", "run"]
        extends:
            service: code

    api:
        container_name: api
        command: ["crudik", "run", "api"]
        expose:
            - 5000
        extends:
            service: code

    db:
        container_name: db
        image: postgis/postgis:17-master
        env_file:
            - ./.config/dev/.env.dev.pg
        volumes:
            - ./.config/init.sql:/docker-entrypoint-initdb.d/init.sql
        expose:
            - 5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s

    minio:
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
        container_name: minio
        expose:
            - 9000
        ports:
            - "9001:9001"
        command: server /data --console-address ":9001"
        env_file:
            - ./.config/dev/.env.dev.minio
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 2s

    nginx-s3-gateway:
        image: nginxinc/nginx-s3-gateway:latest-njs-oss-20250908
        container_name: nginx-s3-gateway
        env_file:
            - ./.config/dev/.env.dev.minio
        expose:
            - 80
