services:
    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        depends_on:
            - api

    tests:
        restart: no
        build:
            dockerfile: test.Dockerfile
        extends:
            file: docker-compose.base.yml
            service: code
        container_name: tests
        command: [ "pytest", "-vvv", "tests/integration/payment"]
        environment:
            - API_URL=http://nginx:80
        depends_on:
            nginx:
                condition: service_healthy

    swagger-ui:
        extends:
            file: docker-compose.base.yml
            service: swagger-ui
        depends_on:
            - api

    api:
        extends:
            file: docker-compose.base.yml
            service: api
        depends_on:
            db:
                condition: service_healthy
            nginx-s3-gateway:
                condition: service_started

    db:
        extends:
            file: docker-compose.base.yml
            service: db

    minio:
        extends:
            file: docker-compose.base.yml
            service: minio

    nginx-s3-gateway:
        extends:
            file: docker-compose.base.yml
            service: nginx-s3-gateway
        depends_on:
            minio:
                condition: service_healthy