services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        expose:
            - 3000
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

    nginx:
        image: nginx:1.23.3
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./.config/dev/nginx.dev.conf:/etc/nginx/nginx.conf
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/ping/" ]
            interval: 4s

    swagger-ui:
        image: swaggerapi/swagger-ui
        expose:
            - 8080
        environment:
            - BASE_URL=/docs
            - SWAGGER_JSON=/var/www/static/openapi.yml
        volumes:
            - ./docs/openapi.yml:/var/www/static/openapi.yml
        restart: unless-stopped

    code:
        restart: on-failure
        build: .
        env_file:
            - "./.config/dev/.env.dev"
        volumes:
            - "./src/loyalty/adapters/db/alembic/migrations/versions/:/home/app/src/loyalty/adapters/db/alembic/migrations/versions/"

    api:
        container_name: api
        command: [ "crudik", "run", "api" ]
        expose:
            - 5000
        extends:
            service: code

    db:
        container_name: persistence
        image: postgis/postgis:14-3.5-alpine
        env_file:
            - ./.config/dev/.env.dev.pg
        volumes:
            - ./.config/init.sql:/docker-entrypoint-initdb.d/init.sql
        expose:
            - 5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 2s

    minio:
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
        container_name: minio
        expose:
            - 9000
        ports:
          - "9001:9001"
        command: server /data --console-address ":9001"
        env_file:
            - ./.config/dev/.env.dev.minio
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 2s

    nginx-s3-gateway:
        image: ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest-njs-oss-20220310
        container_name: nginx-s3-gateway
        env_file:
            - ./.config/dev/.env.dev.minio
        expose:
          - 80