services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        expose:
            - 3000
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

    nginx:
        image: nginx:1.23.3
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/ping/" ]
            interval: 4s
    swagger-ui:
        image: swaggerapi/swagger-ui
        expose:
            - 8080
        environment:
            - BASE_URL=/docs
            - SWAGGER_JSON=/var/www/static/openapi.yml
        volumes:
            - ./openapi.yml:/var/www/static/openapi.yml
        restart: unless-stopped

    code:
        restart: on-failure
        build: .
        env_file:
            - ".env.dev"
        volumes:
            - "./src/loyalty/adapters/db/alembic/migrations/versions/:/home/app/src/loyalty/adapters/db/alembic/migrations/versions/"

    api:
        container_name: api
        command: [ "crudik", "run", "api" ]
        expose:
            - 5000
        extends:
            service: code

    db:
        container_name: persistence
        image: postgis/postgis:14-3.5-alpine
        env_file:
            - .env.dev.pg
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        expose:
            - 5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 2s
