FROM python:3.13.3-alpine3.21

ENV APP_HOME=/home/app/
WORKDIR $APP_HOME

RUN mkdir ./src

RUN pip install uv
COPY ./pyproject.toml $APP_HOME
RUN uv pip install -e ".[test]" --system

COPY ./src/ $APP_HOME/src/
COPY ./tests/ $APP_HOME/tests/
