"""['access token']

Revision ID: 04ed940e263b
Revises: 76e2ef51e3f9
Create Date: 2025-04-07 18:17:22.808462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ed940e263b'
down_revision = '76e2ef51e3f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###