"""['remove tables']

Revision ID: 144632402175
Revises: 1c0e2700f275
Create Date: 2025-04-07 19:24:11.663533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144632402175'
down_revision = '1c0e2700f275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###