"""['loyalty', 'membership']

Revision ID: 156acf76eb1c
Revises: 81979763fc57
Create Date: 2025-05-07 12:10:58.275541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156acf76eb1c'
down_revision = '81979763fc57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_membership',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('loyalty_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loyalty_id'], ['loyalty.loyalty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.alter_column('loyalty', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loyalty', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('loyalty_membership')
    # ### end Alembic commands ###