"""avatar

Revision ID: 1607ff48546d
Revises: 3ed01f87d276
Create Date: 2025-05-14 16:15:47.283991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1607ff48546d'
down_revision = '3ed01f87d276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'avatar_url')
    # ### end Alembic commands ###