"""['remove tables']

Revision ID: 1c0e2700f275
Revises: 8154bfea9b8c
Create Date: 2025-04-07 19:23:46.827330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0e2700f275'
down_revision = '8154bfea9b8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_user')
    op.drop_table('business_user')
    op.alter_column('access_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('business_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'client', ['client_id'], ['client_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'business', ['business_id'], ['business_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    op.drop_column('users', 'client_id')
    op.alter_column('access_token', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('business_user',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], name='business_user_business_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='business_user_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'business_id', name='business_user_pkey')
    )
    op.create_table('client_user',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name='client_user_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='client_user_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'client_id', name='client_user_pkey')
    )
    # ### end Alembic commands ###