"""['название миграции']

Revision ID: 2cc08debc770
Revises: 332991cdce3c
Create Date: 2025-04-15 20:12:46.755557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc08debc770'
down_revision = '332991cdce3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_branch_address_key', 'business_branch', type_='unique')
    op.drop_constraint('business_branch_name_key', 'business_branch', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('business_branch_name_key', 'business_branch', ['name'])
    op.create_unique_constraint('business_branch_address_key', 'business_branch', ['address'])
    # ### end Alembic commands ###