"""['removed email from branch table']

Revision ID: 332991cdce3c
Revises: caa71e855eb8
Create Date: 2025-04-12 16:57:14.790802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332991cdce3c'
down_revision = 'caa71e855eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###