"""['Added business_branch table + changed business table']

Revision ID: 3cab696ef77e
Revises: c6f37c863d6a
Create Date: 2025-04-11 19:22:01.390125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cab696ef77e'
down_revision = 'c6f37c863d6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###