"""['UUID changes']

Revision ID: 3f5d0700735f
Revises: 49b1ad23c23e
Create Date: 2025-05-05 18:18:39.266358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5d0700735f'
down_revision = '49b1ad23c23e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###