"""['table Loyalty added']

Revision ID: 40d2144e6df9
Revises: 4c80e5a0f890
Create Date: 2025-04-29 19:50:36.424453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d2144e6df9'
down_revision = '4c80e5a0f890'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###