"""['added association table for business branches and loyalties']

Revision ID: 49b1ad23c23e
Revises: ca9746177f36
Create Date: 2025-05-04 19:29:17.490672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b1ad23c23e'
down_revision = 'ca9746177f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalties_to_branches_table',
    sa.Column('loyalty_id', sa.UUID(), nullable=True),
    sa.Column('business_branch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_branch_id'], ['business_branch.business_branch_id'], ),
    sa.ForeignKeyConstraint(['loyalty_id'], ['loyalty.loyalty_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loyalties_to_branches_table')
    # ### end Alembic commands ###