"""['table Loyalty added']

Revision ID: 4c80e5a0f890
Revises: 6af2fb97623f
Create Date: 2025-04-29 19:48:05.581252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c80e5a0f890'
down_revision = '6af2fb97623f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###