"""['rm city']

Revision ID: 5493b7169389
Revises: 88abe49d4b69
Create Date: 2025-04-06 19:05:50.503229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5493b7169389'
down_revision = '88abe49d4b69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('city', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###