"""['Changed', 'loyalty', 'table', 'money_per_bonus', 'field', 'type']

Revision ID: 576129839f3b
Revises: 681936ce836c
Create Date: 2025-05-09 19:02:31.457689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576129839f3b'
down_revision = '681936ce836c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loyalty', 'money_per_bonus',
        existing_type=sa.Numeric(10, 2),
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('loyalty', 'money_per_bonus',
            existing_type=sa.Integer,
            nullable=False)

