"""['added', 'unique', 'constraint', 'to', 'loyalty']

Revision ID: 681936ce836c
Revises: 0709f1a35a57
Create Date: 2025-05-07 19:11:23.151533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681936ce836c'
down_revision = '0709f1a35a57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_loyalty_name', 'loyalty', ['name', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_loyalty_name', 'loyalty', type_='unique')
    # ### end Alembic commands ###