"""['table Loyalty added']

Revision ID: 6af2fb97623f
Revises: 89c637e118e2
Create Date: 2025-04-29 19:40:01.238968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as ps

# revision identifiers, used by Alembic.
revision = '6af2fb97623f'
down_revision = '89c637e118e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty',
    sa.Column('loyalty_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=950), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('money_per_bonus', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gender', ps.ENUM('MALE', 'FEMALE', name='gender', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loyalty_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loyalty')
    # ### end Alembic commands ###