"""['money_for_bonus']

Revision ID: 73dcc8b81184
Revises: 77fd8f6092d6
Create Date: 2025-05-07 11:45:35.379621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dcc8b81184'
down_revision = '77fd8f6092d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty', sa.Column('money_for_bonus', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loyalty', 'money_for_bonus')
    # ### end Alembic commands ###