"""['unique index']

Revision ID: 76e2ef51e3f9
Revises: b7c63e7f7cd1
Create Date: 2025-04-07 12:20:40.775723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e2ef51e3f9'
down_revision = 'b7c63e7f7cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'business', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    # ### end Alembic commands ###