"""['payment', '2']

Revision ID: 775b52f50a21
Revises: d21b91bec780
Create Date: 2025-05-10 20:28:22.671776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775b52f50a21'
down_revision = 'd21b91bec780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('loyalty_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('payment_sum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_income', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loyalty_id'], ['loyalty.loyalty_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['loyalty_membership.membership_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###