"""['business not null']

Revision ID: 77fd8f6092d6
Revises: 11540f2fac44
Create Date: 2025-05-06 22:16:04.600617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fd8f6092d6'
down_revision = '11540f2fac44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_branch', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_branch', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###