"""payment_field

Revision ID: 7f6ca81fb803
Revises: b3607ff4aa3e
Create Date: 2025-05-11 19:20:27.016438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6ca81fb803'
down_revision = 'b3607ff4aa3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('business_branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payment', 'business_branch', ['business_branch_id'], ['business_branch_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'business_branch_id')
    # ### end Alembic commands ###