"""['access token 2']

Revision ID: 8154bfea9b8c
Revises: 04ed940e263b
Create Date: 2025-04-07 18:36:14.384381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8154bfea9b8c'
down_revision = '04ed940e263b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token')
    # ### end Alembic commands ###