"""['test']

Revision ID: 81979763fc57
Revises: 73dcc8b81184
Create Date: 2025-05-07 11:46:51.509625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81979763fc57'
down_revision = '73dcc8b81184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###