"""['Removed address column from businessbranches']

Revision ID: 89c637e118e2
Revises: 2cc08debc770
Create Date: 2025-04-16 17:07:00.707543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c637e118e2'
down_revision = '2cc08debc770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_branch', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_branch', sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###