"""['user and client']

Revision ID: 90a9f34dd454
Revises: 2c0a39928206
Create Date: 2025-04-06 07:21:12.495428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a9f34dd454'
down_revision = '2c0a39928206'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###