"""['web user']

Revision ID: 962ae5860807
Revises: 144632402175
Create Date: 2025-04-08 09:25:39.302531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962ae5860807'
down_revision = '144632402175'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_user',
    sa.Column('web_user_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('web_user_id')
    )
    op.create_index(op.f('ix_web_user_username'), 'web_user', ['username'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_web_user_username'), table_name='web_user')
    op.drop_table('web_user')
    # ### end Alembic commands ###