"""['Changed', 'loyalty', 'table', 'money_per_bonus', 'field', 'typef']

Revision ID: a6a23b9da163
Revises: 576129839f3b
Create Date: 2025-05-09 19:03:13.810097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a23b9da163'
down_revision = '576129839f3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###