"""['business']

Revision ID: b7c63e7f7cd1
Revises: 609ea4dbf58f
Create Date: 2025-04-07 08:52:28.287588

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = 'b7c63e7f7cd1'
down_revision = '609ea4dbf58f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('business',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_geospatial_index('idx_business_location', 'business', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('business_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_user')
    op.drop_geospatial_index('idx_business_location', table_name='business', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('business')
    # ### end Alembic commands ###