"""['removed email from branch table']

Revision ID: caa71e855eb8
Revises: d5f2da11ac74
Create Date: 2025-04-12 16:56:18.801610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa71e855eb8'
down_revision = 'd5f2da11ac74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_branch', 'contact_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_branch', sa.Column('contact_email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###