"""['table Loyalty added']

Revision ID: cd493300587b
Revises: 40d2144e6df9
Create Date: 2025-04-29 19:57:15.779316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd493300587b'
down_revision = '40d2144e6df9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###