"""['Added business_branch table + changed business table']

Revision ID: d5f2da11ac74
Revises: 6c26017c7da0
Create Date: 2025-04-11 19:58:09.572756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f2da11ac74'
down_revision = '6c26017c7da0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_branch_business_id_fkey', 'business_branch', type_='foreignkey')
    op.create_foreign_key(None, 'business_branch', 'business', ['business_id'], ['business_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_branch', type_='foreignkey')
    op.create_foreign_key('business_branch_business_id_fkey', 'business_branch', 'business', ['business_id'], ['business_id'], ondelete='SET NULL')
    # ### end Alembic commands ###