"""remove_nullable

Revision ID: fa26c269fcd5
Revises: 7f6ca81fb803
Create Date: 2025-05-13 15:50:48.228260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa26c269fcd5'
down_revision = '7f6ca81fb803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loyalty', 'money_for_bonus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loyalty', 'money_for_bonus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###