openapi: 3.0.0
info:
    title: Loyalty API
    version: 1.0.0

paths:
    /login/:
        post:
            summary: Login user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LoginForm"
            responses:
                "200":
                    description: Successfully login
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AccessToken"
                "422":
                    description: Bad Request
                "403":
                    description: Login failed

    /client/:
        post:
            summary: Create a new client
            tags:
                - Client
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ClientWebSignUpForm"
            responses:
                "200":
                    description: Successfully created client
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Client"
                "422":
                    description: Bad Request
                "409":
                    description: User with this username already exists
    /business/:
        post:
            summary: Create a new business
            tags:
                - Business
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BusinessWebSignUpForm"
            responses:
                "200":
                    description: Successfully created business
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Business"
                "422":
                    description: Bad Request
                "409":
                    description: User with this username already exists or business with this name already exists
components:
    securitySchemes:
        auth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        ClientWebSignUpForm:
            type: object
            required:
                - username
                - password
                - client_data
            properties:
                username:
                    type: string
                    minLength: 3
                    maxLength: 100
                    example: "john_doe"
                password:
                    type: string
                    minLength: 6
                    maxLength: 100
                    example: "securePassword123"
                    format: password
                client_data:
                    $ref: "#/components/schemas/ClientForm"

        BusinessWebSignUpForm:
            type: object
            required:
                - username
                - password
                - business_data
            properties:
                username:
                    type: string
                    minLength: 3
                    maxLength: 100
                    example: "business"
                password:
                    type: string
                    minLength: 6
                    maxLength: 100
                    example: "securePassword123"
                    format: password
                business_data:
                    $ref: "#/components/schemas/BusinessForm"

        LoginForm:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                    minLength: 3
                    maxLength: 100
                    example: "john_doe"
                password:
                    type: string
                    minLength: 6
                    maxLength: 100
                    example: "securePassword123"
                    format: password

        ClientForm:
            type: object
            required:
                - full_name
                - age
                - gender
                - phone
                - lon
                - lat
            properties:
                full_name:
                    type: string
                    minLength: 4
                    maxLength: 250
                    example: "John Doe"
                age:
                    type: integer
                    minimum: 0
                    maximum: 100
                    example: 30
                gender:
                    type: string
                    enum: ["MALE", "FEMALE", "OTHER"]
                    example: "MALE"
                phone:
                    type: string
                    example: "+79281859225"
                lon:
                    type: float
                    minimum: -90
                    maximum: 90
                    example: 37.6156
                lat:
                    type: float
                    minimum: -180
                    maximum: 180
                    example: 55.7522
        BusinessForm:
            type: object
            required:
                - name
                - contact_email
                - lon
                - lat
            properties:
                name:
                    type: string
                    minLength: 2
                    maxLength: 250
                    example: "ООО БНАЛ"
                contact_phone:
                    type: string
                    example: "+79281659225"
                contact_email:
                    type: string
                    format: email
                    example: "structnull@yandex.ru"
                lon:
                    type: float
                    minimum: -90
                    maximum: 90
                    example: 37.6156
                lat:
                    type: float
                    minimum: -180
                    maximum: 180
                    example: 55.7522

        Client:
            type: object
            required:
                - client_id
                - full_name
                - age
                - gender
                - phone
                - lon
                - lat
                - created_at
            properties:
                client_id:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-41d4-a716-446655440000"
                full_name:
                    type: string
                    example: "John Doe"
                age:
                    type: integer
                    example: 30
                gender:
                    type: string
                    enum: ["MALE", "FEMALE"]
                    example: "MALE"
                phone:
                    type: string
                    example: "+79281559535"
                lon:
                    type: float
                    example: 37.6156
                lat:
                    type: float
                    example: 55.7522
                created_at:
                    type: string
                    format: date-time
        Business:
            type: object
            required:
                - business_id
                - name
                - contact_email
                - contact_phone
                - lon
                - lat
                - created_at
            properties:
                business_id:
                    type: string
                    format: uuid
                    example: "550e8400-e29b-49d4-a716-446655440000"
                name:
                    type: string
                    example: "ООО Бнал"
                contact_phone:
                    type: string
                    nullable: true
                    example: "+79281559535"
                contact_email:
                    type: string
                    format: email
                    example: "+79281559535"
                lon:
                    type: float
                    example: 37.6156
                lat:
                    type: float
                    example: 55.7522
                created_at:
                    type: string
                    format: date-time
        AccessToken:
            type: object
            required:
                - token_info
                - token
            properties:
                token_info:
                    type: object
                    required:
                        - entity_id
                        - role
                    properties:
                        entity_id:
                            type: string
                            format: uuid
                            example: "550e8400-e29b-41d4-a716-446655440000"
                        role:
                            type: string
                            enum: ["client", "business"]
                            example: "client"
                token:
                    type: string
